### ISSUE TITLE
md文件当文件名含有中文时预览错误

### ISSUE THREAD

**Issue by chengpengzhao** [reruin/sharelist#108]
报错：   Error -500
```
Error
Looks like something broke!

        
TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:137:13)
    at Object.request (http.js:39:10)
    at Object.request (https.js:245:15)
    at Request.start (/sharelist/node_modules/request/request.js:755:32)
    at Request.end (/sharelist/node_modules/request/request.js:1525:10)
    at end (/sharelist/node_modules/request/request.js:567:14)
    at Immediate._onImmediate (/sharelist/node_modules/request/request.js:581:7)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by reruin** [comment]
能将这份md文件发出来测试下吗？我在本地未复现此情况。
