### ISSUE TITLE
在线播放视频的时候，一直报错，不知道怎么回事

### ISSUE THREAD

**Issue by LFG2019347** [reruin/sharelist#115]
Error: options.uri is a required argument
    at Request.init (/root/sharelist/node_modules/request/request.js:234:31)
    at new Request (/root/sharelist/node_modules/request/request.js:130:8)
    at request (/root/sharelist/node_modules/request/index.js:54:10)
    at /root/sharelist/app/utils/http.js:64:5
    at new Promise (<anonymous>)
    at Function.http.get (/root/sharelist/app/utils/http.js:63:10)
    at Object.file (/root/sharelist/plugins/drive.gd.js:166:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
提供下你的页面地址。
