### ISSUE TITLE
挂载多个后端 OneDrive 路径匹配问题

### ISSUE THREAD

**Issue by jitingcn** [reruin/sharelist#152]
不知道这个标题是否合适...

挂载了两个目录
OneDriveApi 挂载为 `onedrive` 到 `/vtuber/kurumi`
本地文件 挂载为 `local` 到 `/srv/http`

本地文件可以正常通过 https://host/local 访问
OneDriveApi 访问 https://host/onedrive 报错：
```
Error
Looks like something broke!

        
TypeError: Cannot read property 'split' of undefined
    at folder (/usr/share/webapps/sharelist/plugins/drive.od.js:105:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.file (/usr/share/webapps/sharelist/plugins/drive.od.js:187:18)
    at async Object.ls (/usr/share/webapps/sharelist/app/plugins/cmd.core.js:50:16)
    at async ShareList.path (/usr/share/webapps/sharelist/app/services/sharelist.js:62:18)
    at async Object.index (/usr/share/webapps/sharelist/app/controllers/sharelist.js:99:18)
    at async /usr/share/webapps/sharelist/app/routers/page.js:14:7
    at async module.exports (/usr/share/webapps/sharelist/app/middleware/koa-install.js:5:5)
    at async /usr/share/webapps/sharelist/app/index.js:70:3
    at async /usr/share/webapps/sharelist/node_modules/koa-static-cache/index.js:82:16
    at async /usr/share/webapps/sharelist/node_modules/koa-static-cache/index.js:62:36
    at async module.exports (/usr/share/webapps/sharelist/app/middleware/koa-paths.js:133:3)
    at async module.exports (/usr/share/webapps/sharelist/app/middleware/koa-addr.js:16:3)
```

### 测试
只挂载 OneDrive 可以正常访问目标文件夹
把 OneDriveApi 挂载为 `vtuber` 到 `/vtuber/kurumi` 后可以正常访问目标文件夹
把 OneDriveApi 挂载为 `kurumi` 到 `/vtuber/kurumi` 后可以正常访问目标文件夹
把 OneDriveApi 挂载为 `wtf` 到 `/` 后可以正常访问 OneDrive 根目录

因此判断可能是子目录路径匹配上有问题... 希望可以修复

**Comment by reruin** [comment]
挂载标示 不能作为 挂载路径。
目前的挂载标示有：gd、googledrive、gda、od、onedrive、oda、odb、odc、github、h5ai、webdav、http、https、sl、lanzou、ctc、ctcc、cy。
