### ISSUE TITLE
Error occurred on downloading file

### ISSUE THREAD

**Issue by ttsunboy** [reruin/sharelist#154]
Error occurred when trying to download file via Google Drive folder ID:
```
Error: options.uri is a required argument
    at Request.init (/root/sharelist/node_modules/request/request.js:234:31)
    at new Request (/root/sharelist/node_modules/request/request.js:130:8)
    at request (/root/sharelist/node_modules/request/index.js:54:10)
    at /root/sharelist/app/utils/http.js:64:5
    at new Promise (<anonymous>)
    at Function.http.get (/root/sharelist/app/utils/http.js:63:10)
    at Object.file (/root/sharelist/plugins/drive.gd.js:166:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
File list is successfully loaded.

Target folder link: https://drive.google.com/drive/folders/0B-tdl3VvPeOOYm12Wm80V04wdDQ
File on https://zibo.yeyi.site/3_40_22.zip

**Comment by Mit2g** [comment]
Try to update sharelist and re-authorize your google drive api
