### ISSUE TITLE
Error - 500

### ISSUE THREAD

**Issue by AKdfx56416** [reruin/sharelist#171]
Looks like something broke!
ReferenceError: URLSearchParams is not defined
    at parseConfig (/root/sharelist/app/middleware/koa-paths.js:31:16)
    at module.exports (/root/sharelist/app/middleware/koa-paths.js:78:8)
    at dispatch (/root/sharelist/node_modules/koa-compose/index.js:42:32)
    at module.exports (/root/sharelist/app/middleware/koa-addr.js:16:9)
    at dispatch (/root/sharelist/node_modules/koa-compose/index.js:42:32)
    at filter (/root/sharelist/node_modules/koa-json/index.js:25:12)
    at dispatch (/root/sharelist/node_modules/koa-compose/index.js:42:32)
    at /root/sharelist/node_modules/koa-body/index.js:148:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by MasterOfStar** [comment]
update之后出现同样的错误

**Comment by reruin** [comment]
已修复，有处修改 不兼容 node < 10。
