### ISSUE TITLE
请问怎么挂载群晖的WebDAV？

### ISSUE THREAD

**Issue by pirately** [reruin/sharelist#174]
根据教程：
挂载标示：webdav  
挂载路径：  
  https://webdavserver.com:1222/path   
  https://username:password@webdavserver.com:1222/path   
  https://username:password@webdavserver.com:1222/?acceptRanges=none

后面两个，都是只能看到群晖WebDAV的所有文件的列表，但是打开具体文件错误。
显示如下：
Error
Looks like something broke!

        
TypeError: /sharelist/app/views/default/detail.pug:6
    4|   header
    5|     .wrap.detail
  > 6|       a.home #{data.name}
    7|       a.download-menu(href=url)
    8|         i.ic.ic-download
    9|   section.wrap

Cannot read property 'name' of null
    at eval (eval at wrap (/sharelist/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:42:62)
    at template (eval at wrap (/sharelist/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:83:72)
    at /sharelist/node_modules/consolidate/lib/consolidate.js:951:16
    at /sharelist/node_modules/consolidate/lib/consolidate.js:161:5
    at Promise._execute (/sharelist/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/sharelist/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/sharelist/node_modules/bluebird/js/release/promise.js:103:10)
    at promisify (/sharelist/node_modules/consolidate/lib/consolidate.js:154:10)
    at exports.pug (/sharelist/node_modules/consolidate/lib/consolidate.js:935:10)
    at getPaths.then.paths (/sharelist/node_modules/koa-views/src/index.js:42:18)
    at <anonymous>
        
     这是为啥？不管加不加/?acceptRanges=none这个，都一样

**Comment by reruin** [comment]
你的群晖webdav连接能否反代出来，私发我测试下？
