### ISSUE TITLE
使用Heroku一键部署的Sharelist无法使用

### ISSUE THREAD

**Issue by youwen233** [reruin/sharelist#184]
使用Heroku一键部署的Sharelist,在管理界面配置好后,设置天翼云账号登陆或Onedrive for business登录都会错误500,前者报错如下
```
Error
Looks like something broke!

        
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
    at ClientRequest.onError (/app/sharelist-master/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
        
```
后者错误如下:
```
Error
Looks like something broke!

        
Error: Invalid URI "./example"
    at Request.init (/app/sharelist-master/node_modules/request/request.js:276:31)
    at new Request (/app/sharelist-master/node_modules/request/request.js:130:8)
    at request (/app/sharelist-master/node_modules/request/index.js:54:10)
    at /app/sharelist-master/app/utils/http.js:64:5
    at new Promise (<anonymous>)
    at Function.http.get (/app/sharelist-master/app/utils/http.js:63:10)
    at getClient (/app/sharelist-master/plugins/drive.odb.js:33:29)
    at Object.folder (/app/sharelist-master/plugins/drive.odb.js:79:39)
    at process_fast (/app/sharelist-master/app/plugins/cmd.core.js:178:30)
    at Object.ls (/app/sharelist-master/app/plugins/cmd.core.js:55:22)
    at command (/app/sharelist-master/app/services/plugin.js:465:49)
    at ShareList.path (/app/sharelist-master/app/services/sharelist.js:80:26)
    at Object.index (/app/sharelist-master/app/controllers/sharelist.js:104:32)
    at router.all (/app/sharelist-master/app/routers/page.js:14:23)
    at dispatch (/app/sharelist-master/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/app/sharelist-master/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
        
```

**Comment by youwen233** [comment]
https://youwenqwq.herokuapp.com/为部署链接,可随意填写天翼账号测试

**Comment by qz919** [comment]
同样的问题

**Comment by reruin** [comment]
昨天提交的代码有点问题，你重新部署下Herok。

**Comment by 4444w** [comment]
> 昨天提交的代码有点问题，你重新部署下Herok。

重新部署heroku也不行啊

**Comment by youwen233** [comment]
> 昨天提交的代码有点问题，你重新部署下Herok。

跟进：重新部署后不会出现错误，但会提示验证码识别接口无法使用，请问能否提供手动输入验证码的文本框？

**Comment by reruin** [comment]
> > 昨天提交的代码有点问题，你重新部署下Herok。
> 
> 跟进：重新部署后不会出现错误，但会提示验证码识别接口无法使用？

验证码识别接口不太稳定。你可以使用moeclub 的接口，参考 https://github.com/reruin/sharelist/issues/193#issuecomment-636313469 。

**Comment by youwen233** [comment]
> > > 昨天提交的代码有点问题，你重新部署下Herok。
> > 
> > 
> > 跟进：重新部署后不会出现错误，但会提示验证码识别接口无法使用？
> 
> 验证码识别接口不太稳定。你可以使用moeclub 的接口，参考 [#193 (comment)](https://github.com/reruin/sharelist/issues/193#issuecomment-636313469) 。

好的,感谢

**Comment by youwen233** [comment]
重新部署后提示
```
unknown blob
=!= Build failed due to an error:
=!= push step: exit status 1
If this persists, please contact us at https://help.heroku.com/.
```
```
Build app Hide build log
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
```

**Comment by youwen233** [comment]
> 重新部署后提示
> 
> ```
> unknown blob
> =!= Build failed due to an error:
> =!= push step: exit status 1
> If this persists, please contact us at https://help.heroku.com/.
> ```
> 
> ```
> Build app Hide build log
> There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
> ```

已恢复正常,在测试

**Comment by youwen233** [comment]
已可以使用，另外提一句，目前不知道天翼网盘如何指定挂载目录，目前挂载目录是`//1*********8/?password=**************`
想要挂载目录名为DL的文件夹，请问如何更改？

**Comment by reruin** [comment]
> 已可以使用，另外提一句，目前不知道天翼网盘如何指定挂载目录，目前挂载目录是`//1*********8/?password=**************`
> 想要挂载目录名为DL的文件夹，请问如何更改？

1. 参考 readme ```//用户名/初始文件夹ID?password=密码```
2. 如何获取文件夹ID：https://github.com/reruin/sharelist/issues/150

**Comment by youwen233** [comment]
> > 已可以使用，另外提一句，目前不知道天翼网盘如何指定挂载目录，目前挂载目录是`//1*********8/?password=**************`
> > 想要挂载目录名为DL的文件夹，请问如何更改？
> 
> 1. 参考 readme `//用户名/初始文件夹ID?password=密码`
> 2. 如何获取文件夹ID：#150

感谢，没仔细看readme，对不起啦
