### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by vcheckzen** [reruin/sharelist#185]
设置任何盘，涉及网络请求时，网页都出现如下错误，npm 未设置代理

```js
Error
Looks like something broke!

        
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
    at ClientRequest.onError (/usr/local/etc/sharelist/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by vcheckzen** [comment]
破案了，作者 [提交](https://github.com/reruin/sharelist/commit/8692477d52fc6c020fbf2176ab2eec29c4783bfa#diff-d4b2c21ef9584f7593993ee3ced065cc) 时没有把调试代码注释

**Comment by NUSC** [comment]
今天部署，我也是遇到这个了

**Comment by reruin** [comment]
> 今天部署，我也是遇到这个了

如 @vcheckzen 所言。更新下代码。

**Comment by NUSC** [comment]
> > 今天部署，我也是遇到这个了
> 
> 如 @vcheckzen 所言。更新下代码。

恩，改了，成功了。

**Comment by NUSC** [comment]
@reruin 还有天翼云一个目录最多只能100个文件吗？发现后面都没了。

**Comment by reruin** [comment]
已修复 https://github.com/reruin/sharelist/issues/192
