### ISSUE TITLE
id错误500，GD,OG aip无限重试

### ISSUE THREAD

**Issue by flyvicky** [reruin/sharelist#188]
Error
Looks like something broke!

        
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080
    at ClientRequest.onError (/home/sharelist/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

![image](https://user-images.githubusercontent.com/55944584/82804222-7c9a2480-9eb4-11ea-9111-7f3703c4fb46.png)

**Comment by reruin** [comment]
重新拉下代码，误上传了一段调试代码。
