### ISSUE TITLE
当目录里含有README.md文件且在管理面板里开启显示readme之后报错500

### ISSUE THREAD

**Issue by houzizhe123** [reruin/sharelist#189]
## 已经尝试了markdown各种语法，发现只要有README.md且设置显示readme就会报错。报错代码如下
Error
Looks like something broke!
Error: options.uri is a required argument
    at Request.init (/root/sharelist/node_modules/request/request.js:234:31)
    at new Request (/root/sharelist/node_modules/request/request.js:130:8)
    at request (/root/sharelist/node_modules/request/index.js:54:10)
    at /root/sharelist/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at http (/root/sharelist/app/utils/http.js:12:12)
    at fetchData (/root/sharelist/plugins/drive.189cloud.js:321:20)
    at Object.file (/root/sharelist/plugins/drive.189cloud.js:413:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
请说下 readme 所在的挂载盘类型 。

**Comment by houzizhe123** [comment]
> 请说下 readme 所在的挂载盘类型 。

天翼云盘 cookie版
