### ISSUE TITLE
和彩云的文件夹无法打开

### ISSUE THREAD

**Issue by lzh000307** [reruin/sharelist#196]
挂载完和彩云后，根目录的文件可以正常下载和预览，但是文件夹无法打开，点击任意文件夹后提示：
```
Error
Looks like something broke!

        
TypeError: Cannot read property 'ETagOprType' of null
    at children.concat.map.file (/root/sharelist/plugins/drive.caiyun.js:388:27)
    at Array.map (<anonymous>)
    at Object.folder (/root/sharelist/plugins/drive.caiyun.js:387:81)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by reruin** [comment]
已修复。
