### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Omoinemie** [reruin/sharelist#197]
环境版本：
node: 12.17
npm: 6.14.4
pm2: 4.4.0
错误页：
`Error
Looks like something broke!

        
Error: Invalid URI "./example"
    at Request.init (/root/sharelist/node_modules/request/request.js:276:31)
    at new Request (/root/sharelist/node_modules/request/request.js:130:8)
    at request (/root/sharelist/node_modules/request/index.js:54:10)
    at /root/sharelist/app/utils/http.js:64:5
    at new Promise (<anonymous>)
    at Function.http.get (/root/sharelist/app/utils/http.js:63:10)
    at getClient (/root/sharelist/plugins/drive.odb.js:33:29)
    at Object.folder (/root/sharelist/plugins/drive.odb.js:79:39)
    at process_fast (/root/sharelist/app/plugins/cmd.core.js:178:30)
    at Object.ls (/root/sharelist/app/plugins/cmd.core.js:55:22)
    at command (/root/sharelist/app/services/plugin.js:535:49)
    at ShareList.path (/root/sharelist/app/services/sharelist.js:80:26)
    at Object.index (/root/sharelist/app/controllers/sharelist.js:142:32)
    at /root/sharelist/app/routers/page.js:14:23
    at dispatch (/root/sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/root/sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)`

**Comment by reruin** [comment]
后台检查下 挂载方式是否有误。

**Comment by Omoinemie** [comment]
后台也进不去
yun.vomiku.com

**Comment by reruin** [comment]
> 后台也进不去
> yun.vomiku.com

从这个地址进 https://yun.vomiku.com/manage

**Comment by reruin** [comment]
> 后台也进不去
> yun.vomiku.com

请问你的问题解决了没？

**Comment by Omoinemie** [comment]
解决了，谢谢
