### ISSUE TITLE
挂载的天翼云，打开txt，出现error 500

### ISSUE THREAD

**Issue by kexuebin** [reruin/sharelist#198]
Error

Looks like something broke!

        
Error: options.uri is a required argument
    at Request.init (/www/wwwroot/pan.baipu.com/node_modules/request/request.js:234:31)
    at new Request (/www/wwwroot/pan.baipu.com/node_modules/request/request.js:130:8)
    at request (/www/wwwroot/pan.baipu.com/node_modules/request/index.js:54:10)
    at /www/wwwroot/pan.baipu.com/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at http (/www/wwwroot/pan.baipu.com/app/utils/http.js:12:12)
    at fetchData (/www/wwwroot/pan.baipu.com/plugins/drive.189cloud.js:327:20)
    at Object.file (/www/wwwroot/pan.baipu.com/plugins/drive.189cloud.js:419:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by kexuebin** [comment]
另外访问pdf总是提示：Forbidden，
Unexpected server response.
PDF.js v2.6.2 (build: 8fc1126b)
Message: Unexpected server response (401) while retrieving PDF "http://pan.baipu.com/%E6%88%91%E7%9A%84%E6%96%87%E6%A1%A3/%E5%8C%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%9B%BE%E4%B9%A6%E9%A6%86%E9%A6%86%E8%97%8F%E5%96%84%E6%9C%AC%E5%8C%BB%E4%B9%A6%206%20%20%E6%AD%A3%E9%AA%A8%E8%8C%83.pdf?t=5738d00a6faec88e851571e55ea2cae0".
