### ISSUE TITLE
大佬，天翼企业云盘挂载多层文件夹进入报错

### ISSUE THREAD

**Issue by KyAaron** [reruin/sharelist#212]
挂载没问题，第一层是选企业，第二层是选空间，第三层才是目录(该空间下的根目录)，这里的文件正常显示，下一层文件夹里的文件也能正常显示，再下一层就报错!Error500

Error
Looks like something broke!

        
Error: options.uri is a required argument
    at Request.init (/www/wwwroot/dl.ouaone.xyz/node_modules/request/request.js:234:31)
    at new Request (/www/wwwroot/dl.ouaone.xyz/node_modules/request/request.js:130:8)
    at request (/www/wwwroot/dl.ouaone.xyz/node_modules/request/index.js:54:10)
    at /www/wwwroot/dl.ouaone.xyz/app/utils/http.js:13:7
    at new Promise (<anonymous>)
    at Object.http [as request] (/www/wwwroot/dl.ouaone.xyz/app/utils/http.js:12:12)
    at CTCB.fetchData (/www/wwwroot/dl.ouaone.xyz/plugins/drive.189cloud.business.js:410:32)
    at CTCB.path (/www/wwwroot/dl.ouaone.xyz/plugins/drive.189cloud.business.js:599:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
已修复。更新代码后，后台管理 清下缓存。
