### ISSUE TITLE
TypeError: Cannot read property 'cache_refresh_dir' of undefined

### ISSUE THREAD

**Issue by Ice-Hazymoon** [reruin/sharelist#23]
# 错误日志

```
TypeError: Cannot read property 'cache_refresh_dir' of undefined
      at Object.folder (C:\Users\imiku\Downloads\sharelist-master\plugins\drive.gd.js:30:54)
      at ShareList.path (C:\Users\imiku\Downloads\sharelist-master\app\services\index.js:104:29)
      at index (C:\Users\imiku\Downloads\sharelist-master\app\controllers\sharelist.js:54:30)
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
      at next (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
      at C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\lib\router.js:346:16
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
      at next (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
      at module.exports (C:\Users\imiku\Downloads\sharelist-master\app\middleware\koa-sharelist-install.js:5:11)
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
      at next (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
      at C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\lib\router.js:346:16
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
      at C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-router\lib\router.js:351:31)
      at dispatch (C:\Users\imiku\Downloads\sharelist-master\node_modules\koa-compose\index.js:42:32)
```

# 问题

安装成功后首次跳转文件内容正常显示，刷新页面或者点击某个文件、文件夹后返回 `Error - 500`，再次刷新也没用

# 环境

node版本：v10.9.0
npm版本：6.4.1
系统：windows10 专业版 64位

# Google Drive 目录树

- test（共享的目录）
  - 70624207_p0.jpg（图片文件）
  - test（文件夹）

# db.json

```json
{
  "hash": {
    "gd:19roZgERX8q1u_3LL3Sr-kNloho7sg8BM": {
      "id": "19roZgERX8q1u_3LL3Sr-kNloho7sg8BM",
      "type": "folder",
      "protocol": "gd",
      "children": [
        {
          "id": "1vkijyGPVo5btjqF46oWiPboUWbLunG-6",
          "name": "无标题文件夹",
          "ext": null,
          "protocol": "gd",
          "parent": "19roZgERX8q1u_3LL3Sr-kNloho7sg8BM",
          "mime": "application/vnd.google-apps.folder",
          "created_at": "2018-11-02",
          "updated_at": "2018-11-02",
          "size": null,
          "type": "folder"
        },
        {
          "id": "1DRxyM18ZEnCceLxVszN-1Uv5L2UGtdxY",
          "name": "70624207_p0.jpg",
          "ext": "jpg",
          "protocol": "gd",
          "parent": "19roZgERX8q1u_3LL3Sr-kNloho7sg8BM",
          "mime": "image/jpeg",
          "created_at": "2018-11-02",
          "updated_at": "2018-11-02",
          "size": 383215
        }
      ],
      "updated_at": 1541123838874
    }
  }
}
```

# config.json

```json
{"port":33001,"enabled_proxy":0,"enabled_proxy_header":0,"cache_refresh_dir":900000,"cache_refresh_file":300000,"token":"test123","title":"ShareList","path":[{"name":"google","path":"gd:19roZgERX8q1u_3LL3Sr-kNloho7sg8BM"}]}
```

**Comment by Ice-Hazymoon** [comment]
大概看了下发现 `app\services\plugin.js` 和 `app\config.js` 相互引用，导致 config 为空对象，所以出现了上面的bug

**Comment by reruin** [comment]
最近结构大调整天，代码尚未稳定。试一下现在的版本([2bc079](https://github.com/reruin/sharelist/tree/92ec5b7054cf1c9e03b4c9ea6f502b4110344895))。
