### ISSUE TITLE
Onedrive for business Issue

### ISSUE THREAD

**Issue by anjofael** [reruin/sharelist#24]
TypeError: Cannot read property 'drive' of undefined
    at getDrive (/app/app/services/plugin.js:118:24)
    at ShareList.path (/app/app/services/sharelist.js:85:18)
    at <anonymous>

**Comment by reruin** [comment]
It has been fixed. You should clear the cache before you apply update.  
已经修复，更新后最好清掉缓存目录（cache目录下所有内容）
