### ISSUE TITLE
Caiyun无法绑定账号

### ISSUE THREAD

**Issue by Liang147258** [reruin/sharelist#264]
Caiyun在自动挂载向导时，输入账号密码后直接报错：
TypeError: Cannot read property 'join' of undefined
    at Manager.create (/sharelist/plugins/drive.caiyun.js:217:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

看源代码里面还用的caiyun.feixin.10086.cn域名，但实际上Caiyun已经使用c.139.com域名了。

**Comment by reruin** [comment]
此插件需要重新开发。

**Comment by reruin** [comment]
已完成适配。

**Comment by Liang147258** [comment]
刚刚重新下载配置最新的docker后（群晖），重新通过/引导绑定和彩云，还是报错。
TypeError: Cannot read property 'contentInfo' of undefined
    at CY.path (/sharelist/plugins/drive.caiyun.js:711:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
