### ISSUE TITLE
和彩云无法进行挂载，显示错误

### ISSUE THREAD

**Issue by nuyoahaoyun** [reruin/sharelist#266]
挂载和彩云，输入账号密码挂载提示错误，

Error
Looks like something broke!

        
TypeError: Cannot read property 'join' of undefined
    at Manager.create (/root/sharelist/plugins/drive.caiyun.js:217:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async prepare (/root/sharelist/plugins/drive.caiyun.js:421:20)
    at async Object.folder (/root/sharelist/plugins/drive.caiyun.js:450:19)
    at async process_fast (/root/sharelist/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/root/sharelist/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/root/sharelist/app/services/sharelist.js:112:20)
    at async Object.index (/root/sharelist/app/controllers/sharelist.js:164:18)
    at async /root/sharelist/app/routers/page.js:14:7
    at async module.exports (/root/sharelist/app/middleware/koa-install.js:5:5)
    at async /root/sharelist/app/index.js:70:3
    at async /root/sharelist/node_modules/koa-static-cache/index.js:39:63
    at async /root/sharelist/node_modules/koa-static-cache/index.js:39:63
    at async module.exports (/root/sharelist/app/middleware/koa-paths.js:165:3)
    at async module.exports (/root/sharelist/app/middleware/koa-addr.js:16:3)

**Comment by reruin** [comment]
是的，彩云官方换页面了。目前正在适配。
相关 #264

**Comment by reruin** [comment]
已完成适配。

**Comment by nuyoahaoyun** [comment]
> 已完成适配。

我重新安装程序后还是原来一样的错误，不知道是不是我自己的原因

**Comment by reruin** [comment]
> > 已完成适配。
> 
> 我重新安装程序后还是原来一样的错误，不知道是不是我自己的原因

按照一下顺序操作：
1.删除挂载。
2.清除下缓存。
3. 重新设置挂载。
