### ISSUE TITLE
能不能换端口，然后好像不支持中文？

### ISSUE THREAD

**Issue by Thiasap** [reruin/sharelist#28]
我的域名开了https，然后端口可以自定义么……
还有就是中文文件夹不能打开，中文名文件还没试过
然后流量的问题，流量……走的服务器的流量？预览是不是也是服务器的流量？

**Comment by Nehalem-Lf** [comment]
https与端口无关，随便用个caddy把二级域名指向33001就可以了，支持中文，流量在manager里面可选

**Comment by Thiasap** [comment]
我这边中文名文件夹打开报错
[http://od.thiasap.cn:33001/](url)
具体报错：
```
Error
Looks like something broke!
        
TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:137:13)
    at Object.request (http.js:38:10)
    at Object.request (https.js:245:15)
    at Request.start (/data/wwwroot/OneDrive/node_modules/request/request.js:751:32)
    at Request.end (/data/wwwroot/OneDrive/node_modules/request/request.js:1511:10)
    at end (/data/wwwroot/OneDrive/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/data/wwwroot/OneDrive/node_modules/request/request.js:578:7)
    at Immediate.args.(anonymous function) [as _onImmediate] (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by reruin** [comment]
能否提供下目录 id

**Comment by Thiasap** [comment]
> 能否提供下目录id

https://freeshadow-my.sharepoint.com/:f:/g/personal/thiasap_abcda_tech/El6xlwrfvhVNuv7scslrkcEBH_MEF6e_ilLJviJr-Qm_Zw?e=exJI1i

**Comment by reruin** [comment]
此目录访问时提示需要登录。

**Comment by reruin** [comment]
此bug是onedrive的字符转义所导致，现已修复。

**Comment by reruin** [comment]
管理里可以设置是否启用中转模式。
