### ISSUE TITLE
天翼企业云盘及和彩云Error

### ISSUE THREAD

**Issue by DingKuiqing** [reruin/sharelist#285]
天翼企业云盘绑定后，进入目录后提示
Error
Looks like something broke!
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at CTCB.path (/root/sharelist/plugins/drive.189cloud.business.js:562:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
和彩云输入账号密码后，点击验证提示
Error
Looks like something broke!
TypeError: Cannot read property 'join' of undefined
    at Manager.create (/root/sharelist/plugins/drive.caiyun.js:217:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
感觉不是最新代码，更新下试试。
