### ISSUE TITLE
Google Drive API error

### ISSUE THREAD

**Issue by rexx0520** [reruin/sharelist#34]
授權後跳轉顯示下列錯誤：
```
Error
Looks like something broke!

        
Error: invalid_request
    at createError (/sharelist/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/sharelist/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/sharelist/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by reruin** [comment]
google drive api 版本还完开发完成。  
目前仅可使用shareid插件版
