### ISSUE TITLE
Lanzou蓝奏云分享的链接不能用了

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#37]
通过蓝奏云分享了几个mp3文件，之前都能正常播放，前天开始突然不能使用了，提示 Error 500

Error

Looks like something broke!
     
TypeError: Cannot read property '0' of null
    at Object.file (/root/gdlist-master/plugins/drive.lanzou.js:150:71)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
        
本人小白一枚，能否请大大看看什么原因呢？谢谢！

**Comment by reruin** [comment]
已修复，请手动更新下。 dockerhub 明天同步。

**Comment by wekingchen** [comment]
更新之后ok了，谢谢：）
