### ISSUE TITLE
bonjour 模块出错? 导致程序无法启动

### ISSUE THREAD

**Issue by pointedhat32167** [reruin/sharelist#375]
`App is running at http://127.0.0.1:33001/
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Service name is already in use on the network
    at /root/sharelist/node_modules/bonjour/lib/registry.js:47:31
    at done (/root/sharelist/node_modules/bonjour/lib/registry.js:117:5)
    at EventEmitter.onresponse (/root/sharelist/node_modules/bonjour/lib/registry.js:107:75)
    at EventEmitter.emit (events.js:326:22)
    at EventEmitter.emit (domain.js:483:12)
    at Socket.<anonymous> (/root/sharelist/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at UDP.onMessage [as onmessage] (dgram.js:921:8)
Emitted 'error' event on Service instance at:
    at /root/sharelist/node_modules/bonjour/lib/registry.js:47:17
`

**Comment by reruin** [comment]
局域网内是否有其他机器运行sharelist？

**Comment by pointedhat32167** [comment]
> 局域网内是否有其他机器运行sharelist？

应该没有, 测试 4 台 vps
debian 10, centos 7, 两个正常

另外 两台 deiban 10 出现同样错误, 分属两家不同 VPS 商家

**Comment by reruin** [comment]
sharelist 申明了 ShareList RSS 和 ShareList WebDAV 两个服务，同网段只要没有运行 sharelist 就不会出这个提示。
方便把 机器账号密码 私发下么？

**Comment by pointedhat32167** [comment]
> sharelist 申明了 ShareList RSS 和 ShareList WebDAV 两个服务，同网段只要没有运行 sharelist 就不会出这个提示。
> 方便把 机器账号密码 私发下么？

好的 怎么发给你?

**Comment by reruin** [comment]
> > sharelist 申明了 ShareList RSS 和 ShareList WebDAV 两个服务，同网段只要没有运行 sharelist 就不会出这个提示。
> > 方便把 机器账号密码 私发下么？
> 
> 好的 怎么发给你?

reruin@gmail.com
