### ISSUE TITLE
Error 500 怎么解决

### ISSUE THREAD

**Issue by VElfGM** [reruin/sharelist#376]
Error
Looks like something broke!

        
TypeError: Cannot read property 'map' of undefined
    at root (E:\Program Files\sharelist\app\plugins\cmd.core.js:98:22)
    at process_fast (E:\Program Files\sharelist\app\plugins\cmd.core.js:121:15)
    at Object.ls (E:\Program Files\sharelist\app\plugins\cmd.core.js:55:22)
    at command (E:\Program Files\sharelist\app\services\plugin.js:613:49)
    at ShareList.path (E:\Program Files\sharelist\app\services\sharelist.js:112:26)
    at Object.index (E:\Program Files\sharelist\app\controllers\sharelist.js:168:32)
    at E:\Program Files\sharelist\app\router.js:29:23
    at dispatch (E:\Program Files\sharelist\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\Program Files\sharelist\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\Program Files\sharelist\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\Program Files\sharelist\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\Program Files\sharelist\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\Program Files\sharelist\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\Program Files\sharelist\node_modules\koa-compose\index.js:42:32)
    at E:\Program Files\sharelist\app\index.js:74:9
    at dispatch (E:\Program Files\sharelist\node_modules\koa-compose\index.js:42:32)

**Comment by WHFo** [comment]
同遇到
Error
Looks like something broke!

        
TypeError: Cannot read property 'map' of undefined
    at root (/home/root/Sharelist/app/plugins/cmd.core.js:98:22)
    at process_fast (/home/root/Sharelist/app/plugins/cmd.core.js:121:15)
    at Object.ls (/home/root/Sharelist/app/plugins/cmd.core.js:55:22)
    at command (/home/root/Sharelist/app/services/plugin.js:613:49)
    at ShareList.path (/home/root/Sharelist/app/services/sharelist.js:112:26)
    at Object.index (/home/root/Sharelist/app/controllers/sharelist.js:168:32)
    at /home/root/Sharelist/app/router.js:29:23
    at dispatch (/home/root/Sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/home/root/Sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /home/root/Sharelist/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/home/root/Sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /home/root/Sharelist/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/home/root/Sharelist/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/home/root/Sharelist/node_modules/koa-compose/index.js:42:32)
    at /home/root/Sharelist/app/index.js:74:9
    at dispatch (/home/root/Sharelist/node_modules/koa-compose/index.js:42:32)

**Comment by reruin** [comment]
@VElfGM @WHFo 清除缓存 并重新挂载。

**Comment by WHFo** [comment]
> @VElfGM @WHFo 清除缓存 并重新挂载。

我是用这个方法安装的
pm2 start app.js --name sharelist --env prod
pm2 save
pm2 startup
启动完之后什么都还没操作，访问ip:33001就报错了。
重新启动后还是报这个错误。

**Comment by liumingye** [comment]
@VElfGM @WHFo 
尝试打开 http://ip:33001/install 进行安装，新版本好像无法跳转到安装页面

**Comment by irainerc** [comment]
> @VElfGM @WHFo 尝试
> 打开[http：// ip：33001 / install](http://ip:33001/install)进行安装，新版本好像无法替换到安装页面

这是对的！感谢！

**Comment by irainerc** [comment]
> @VElfGM @WHFo 尝试
> 打开[http：// ip：33001 / install](http://ip:33001/install)进行安装，新版本好像无法替换到安装页面

你好，我想问一下raidrive挂载webdav要怎么设置啊，之前胡乱弄成功过，现在不知道怎么弄了

**Comment by reruin** [comment]
丢失一条路由。已修复。
