### ISSUE TITLE
189天翼云，每天都报错，都要重启一下

### ISSUE THREAD

**Issue by msn1024** [reruin/sharelist#397]
每天都会出现如下错误提示，重启一下就好，不知是哪里配置错误，还是什么问题，用户名密码登录。
Error
Looks like something broke!

        
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by xiaodiaoz** [comment]
我也是，太烦了 三天两头出错一次

**Comment by iso-lib** [comment]
我的天翼安装后一直正常啊
docker安装的,你试试

**Comment by nangongxiaoxin** [comment]
我的最近也报错，安卓手机访问报错，win10访问报错，但是Ubuntu下的chrome访问正常，而且这个报错只限于其中一个文件夹，别的文件夹正常
`Error
Looks like something broke!

        
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.index (/www/wwwroot/pan.tianhuan.club/app/controllers/sharelist.js:243:56)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
        
      `
