### ISSUE TITLE
挂载天翼云盘，隔几天就报错一次

### ISSUE THREAD

**Issue by xiaodiaoz** [reruin/sharelist#402]
Error
Looks like something broke!

        
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

求教老哥怎么回事

**Comment by reruin** [comment]
等我观察一段时间。
