### ISSUE TITLE
天翼云每隔几天会报错，重启之后就正常了

### ISSUE THREAD

**Issue by yeheigcy** [reruin/sharelist#459]
Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (C:\Users\Administrator\Documents\L4D2\sharelist\plugins\drive.189cloud.js:384:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process_fast (C:\Users\Administrator\Documents\L4D2\sharelist\app\plugins\cmd.core.js:187:17)
    at async Object.ls (C:\Users\Administrator\Documents\L4D2\sharelist\app\plugins\cmd.core.js:55:16)
    at async ShareList.path (C:\Users\Administrator\Documents\L4D2\sharelist\app\services\sharelist.js:112:20)
    at async Object.index (C:\Users\Administrator\Documents\L4D2\sharelist\app\controllers\sharelist.js:186:18)
    at async C:\Users\Administrator\Documents\L4D2\sharelist\app\router.js:29:7
    at async module.exports (C:\Users\Administrator\Documents\L4D2\sharelist\app\middleware\koa-install.js:5:5)
    at async C:\Users\Administrator\Documents\L4D2\sharelist\app\index.js:67:3
    at async C:\Users\Administrator\Documents\L4D2\sharelist\app\index.js:63:3
    at async C:\Users\Administrator\Documents\L4D2\sharelist\node_modules\koa-static-cache\index.js:53:36
    at async module.exports (C:\Users\Administrator\Documents\L4D2\sharelist\app\middleware\koa-paths.js:168:3)

报错如上
我是搭在本地的windows server上的，天翼云是账号密码登录，每当宽带重新拨号之后，公网IP发生变化，访问天翼云的那个目录就会报这个错。

**Comment by yeheigcy** [comment]
另外想问一下windows的环境咋更新
我安装时是 git clone 之后 npm install，直接 node app.js 运行
更新是不是 git pull 之后 npm install 就行了？

**Comment by reruin** [comment]
windows 下 git更新，然后运行 ```npm install```和 ```pm2 restart all```
