### ISSUE TITLE
蓝奏云挂载出现404

### ISSUE THREAD

**Issue by w1915591935** [reruin/sharelist#480]
网站地址:https://xz.yimuapp.cn/
软件目录。蓝奏云的分享链接是还在的。

[https://gitee.com/yuanjiafu1014/yumu/raw/master/2021/04/27/Screenshot_20210427-111844.jpg](url)

**Comment by benzBrake** [comment]
同出现这个情况了

**Comment by benzBrake** [comment]
看了日志，估计要等作者更新了
```
sharelist      |     at Lanzou.path (/sharelist/plugins/drive.lanzou.js:278:70)
sharelist      |     at <anonymous>
sharelist      |     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by w1915591935** [comment]
上去

**Comment by benzBrake** [comment]
> 
> 
> 看了日志，估计要等作者更新了
> 
> ```
> sharelist      |     at Lanzou.path (/sharelist/plugins/drive.lanzou.js:278:70)
> sharelist      |     at <anonymous>
> sharelist      |     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
> ```

@reruin

**Comment by dwf135** [comment]
等好久了 期待作者更新

**Comment by Gyx200911** [comment]
> 等好久了 期待作者更新

应该是蓝奏云服务器的域名改了 我这边更新js文件的里面蓝奏云的域名就可以正常访问了

**Comment by dwf135** [comment]
> > 等好久了 期待作者更新
> 
> 应该是蓝奏云服务器的域名改了 我这边更新js文件的里面蓝奏云的域名就可以正常访问了

请问是改sharelist\plugins\drive.lanzou.js吗  我把lanzous.com改成lanzoui.com和lanzoux.com 重启后还是老样子

**Comment by Gyx200911** [comment]
> > > 等好久了 期待作者更新
> > 
> > 
> > 应该是蓝奏云服务器的域名改了 我这边更新js文件的里面蓝奏云的域名就可以正常访问了
> 
> 请问是改sharelist\plugins\drive.lanzou.js吗 我把lanzous.com改成lanzoui.com和lanzoux.com 重启后还是老样子

窝着也不大行 列表出来了 刚刚发现文件解析还是404

**Comment by Gyx200911** [comment]
> > > 等好久了 期待作者更新
> > 
> > 
> > 应该是蓝奏云服务器的域名改了 我这边更新js文件的里面蓝奏云的域名就可以正常访问了
> 
> 请问是改sharelist\plugins\drive.lanzou.js吗 我把lanzous.com改成lanzoui.com和lanzoux.com 重启后还是老样子

等作者修复一下吧 迷了

**Comment by reruin** [comment]
@benzBrake 已修复。

**Comment by dwf135** [comment]
> @benzBrake 已修复。

感谢作者的更新
