### ISSUE TITLE
挂载google团队盘，有的目录能打开，有的目录出错

### ISSUE THREAD

**Issue by sztuxp** [reruin/sharelist#487]
Error
Looks like something broke!

        
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.index (/sharelist/app/controllers/sharelist.js:243:56)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by sztuxp** [comment]
补充一下，这个目录以前是可以打开的
