### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by qwertyuiop2018** [reruin/sharelist#5]
Error
Looks like something broke!

        
SyntaxError: Unexpected token x in JSON at position 2151
    at JSON.parse (<anonymous>)
    at Object.folder (/root/models/googledrive.js:34:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by reruin** [comment]
解析文件列表异常，可能是 shareid 的问题。方便把id email 给我么。

**Comment by Nehalem-Lf** [comment]
Error
Looks like something broke!

        
SyntaxError: Unexpected token x in JSON at position 127
    at JSON.parse (<anonymous>)
    at Object.folder (/root/gdlist-master/models/googledrive.js:34:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

用了一段时间之后才这样的

**Comment by reruin** [comment]
用最新版试一下。

**Comment by Nehalem-Lf** [comment]
Error: getaddrinfo EAI_AGAIN drive.google.com:443
    at Object._errnoException (util.js:992:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
