### ISSUE TITLE
阿里云盘挂载显示500

### ISSUE THREAD

**Issue by qingfengjiang** [reruin/sharelist#513]
```
Error
Looks like something broke!

        
TypeError: Cannot read property 'body' of undefined
    at Driver.path (/www/wwwroot/node/sharelist/plugins/drive.aliyundrive.js:402:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Driver.folder (/www/wwwroot/node/sharelist/plugins/drive.aliyundrive.js:476:12)
    at async process_fast (/www/wwwroot/node/sharelist/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/www/wwwroot/node/sharelist/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/www/wwwroot/node/sharelist/app/services/sharelist.js:112:20)
    at async Object.index (/www/wwwroot/node/sharelist/app/controllers/sharelist.js:186:18)
    at async /www/wwwroot/node/sharelist/app/router.js:29:7
    at async module.exports (/www/wwwroot/node/sharelist/app/middleware/koa-install.js:5:5)
    at async /www/wwwroot/node/sharelist/app/index.js:67:3
    at async /www/wwwroot/node/sharelist/app/index.js:63:3
    at async /www/wwwroot/node/sharelist/node_modules/koa-static-cache/index.js:53:36
    at async module.exports (/www/wwwroot/node/sharelist/app/middleware/koa-paths.js:168:3)
```
        
      使用的是最新的sharelist

**Comment by jiotong** [comment]
同样情况

**Comment by Nanhumly** [comment]
+1

**Comment by daofeng2015** [comment]
> ```
> Error
> Looks like something broke!
> 
>         
> TypeError: Cannot read property 'body' of undefined
>     at Driver.path (/www/wwwroot/node/sharelist/plugins/drive.aliyundrive.js:402:17)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async Driver.folder (/www/wwwroot/node/sharelist/plugins/drive.aliyundrive.js:476:12)
>     at async process_fast (/www/wwwroot/node/sharelist/app/plugins/cmd.core.js:187:17)
>     at async Object.ls (/www/wwwroot/node/sharelist/app/plugins/cmd.core.js:55:16)
>     at async ShareList.path (/www/wwwroot/node/sharelist/app/services/sharelist.js:112:20)
>     at async Object.index (/www/wwwroot/node/sharelist/app/controllers/sharelist.js:186:18)
>     at async /www/wwwroot/node/sharelist/app/router.js:29:7
>     at async module.exports (/www/wwwroot/node/sharelist/app/middleware/koa-install.js:5:5)
>     at async /www/wwwroot/node/sharelist/app/index.js:67:3
>     at async /www/wwwroot/node/sharelist/app/index.js:63:3
>     at async /www/wwwroot/node/sharelist/node_modules/koa-static-cache/index.js:53:36
>     at async module.exports (/www/wwwroot/node/sharelist/app/middleware/koa-paths.js:168:3)
> ```
> 
> ```
>   使用的是最新的sharelist
> ```

好像是阿里云api炸了...现在正常了..建议判断下api的状态码..
