### ISSUE TITLE
Onedrive V2 挂载报错

### ISSUE THREAD

**Issue by jihuayu** [reruin/sharelist#530]
挂载了世纪互联的Onedrive，打开目录输入basic auth密码时报错
https://github.com/reruin/sharelist/blob/master/plugins/drive.od.js#L105
```
  <-- POST /od
>>>> undefined
  xxx POST /od 500 227ms -

  TypeError: Cannot read property 'split' of undefined
      at folder (/sharelist/plugins/drive.od.js:105:18)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)

  <-- POST /od
>>>> undefined
  xxx POST /od 500 263ms -

  TypeError: Cannot read property 'split' of undefined
      at folder (/sharelist/plugins/drive.od.js:105:18)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)

  <-- GET /manage
  --> GET /manage 200 239ms 17.27kb
```

**Comment by reruin** [comment]
用 onedrive v2 挂载。

**Comment by jihuayu** [comment]
就是用 onedrive v2 挂载的
![image](https://user-images.githubusercontent.com/32858525/122640640-3f45ac00-d133-11eb-8db1-811667c54f50.png)

**Comment by reruin** [comment]
挂载名不要设置为 od ，换一个其他的，然后清除缓存。
