### ISSUE TITLE
挂载阿里云盘后，使用rclone挂载webdav复制报错

### ISSUE THREAD

**Issue by ChirmyRam** [reruin/sharelist#531]
将sharelist部署至heroku，挂载阿里云盘，将sharelist的webdav链接挂载于rclone，rclone lsd命令能够显示文件夹，rclone copy命令复制文件报错，报错如下：
```
Failed to create file system for "ali:/14.png": read metadata failed: <!DOCTYPE html>
<html>
  <head>
    <title>Error - 500</title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <style>
      body {
        padding: 50px 80px;
        font: 14px "Helvetica Neue", Helvetica, sans-serif;
      }

      h1 {
        font-size: 2em;
        margin-bottom: 5px;
      }

      pre {
        font-size: .8em;
      }
    </style>
  </head>
  <body>
    <div id="error">
      <h1>Error</h1>
    <p>Looks like something broke!</p>

      <pre>
        <code>
TypeError: Cannot read property &#39;unshift&#39; of undefined
    at Request.http_propfind (/sharelist/app/controllers/webdav.js:336:15)
    at &lt;anonymous&gt;
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
        </code>
      </pre>

    </div>
  </body>
</html>: 500 Internal Server Error
```

**Comment by reruin** [comment]
请使用新版，目前已完整支持webdav。
