### ISSUE TITLE
同一台服务器起2个服务报错，请问有什么解决方案吗

### ISSUE THREAD

**Issue by itttttta** [reruin/sharelist#549]
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: Service name is already in use on the network
    at /data/wwwroot/Player-web/node_modules/bonjour/lib/registry.js:47:31
    at done (/data/wwwroot/Player-web/node_modules/bonjour/lib/registry.js:117:5)
    at EventEmitter.onresponse (/data/wwwroot/Player-web/node_modules/bonjour/lib/registry.js:107:75)
    at EventEmitter.emit (events.js:322:22)
    at EventEmitter.emit (domain.js:482:12)
    at Socket.<anonymous> (/data/wwwroot/Player-web/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
Emitted 'error' event on Service instance at:
    at /data/wwwroot/Player-web/node_modules/bonjour/lib/registry.js:47:17
    at done (/data/wwwroot/Player-web/node_modules/bonjour/lib/registry.js:117:5)
    [... lines matching original stack trace ...]
    at UDP.onMessage [as onmessage] (dgram.js:924:8)

**Comment by Youwenqwq** [comment]
用docker安装
