### ISSUE TITLE
OneDrive API 无法挂载

### ISSUE THREAD

**Issue by maobowen** [reruin/sharelist#55]
在 OneDrive 挂载向导页面里填入正确的应用机密和应用 ID 后，可以访问 OneDrive 登陆页面并赋予权限，但再次重定向之后就报错：

```
TypeError: currentDrive.split is not a function or its return value is not iterable
    at Object.folder (/home/steven/sharelist/plugins/drive.od.api.js:282:37)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ShareList.path (/home/steven/sharelist/app/services/sharelist.js:103:16)
    at async Object.index (/home/steven/sharelist/app/controllers/sharelist.js:50:16)
    at async /home/steven/sharelist/app/routers/page.js:14:7
    at async module.exports (/home/steven/sharelist/app/middleware/koa-install.js:5:5)
    at async /home/steven/sharelist/app/index.js:69:3
    at async module.exports (/home/steven/sharelist/app/middleware/koa-paths.js:81:3)
    at async module.exports (/home/steven/sharelist/app/middleware/koa-addr.js:16:3)
```

环境：Ubuntu 18.10, Node v0.12.7

**Comment by reruin** [comment]
升级node到 v8.x 再试一试

**Comment by maobowen** [comment]
不好意思打错了，Node 版本应该是12.7.0。
刚刚重新部署一下后就没有问题了。 个人感觉可能是第一次绑定没有成功，导致 [drive.od.api.js](../blob/master/plugins/drive.od.api.js#L281)  第281行的 `getDrive()` 返回 `null`。我先把这个问题关了，如果后续使用过程中再遇到相同情况再重开吧。

**Comment by reruin** [comment]
此bug在 [#59](https://github.com/reruin/sharelist/issues/59) 复现，现已修复。
