### ISSUE TITLE
天翼 个人网盘 出错了

### ISSUE THREAD

**Issue by at2008** [reruin/sharelist#551]
Error
Looks like something broke!

        
TypeError: Cannot read property 'join' of undefined
    at Manager.create (/root/sharelist/plugins/drive.189cloud.js:141:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Manager.get (/root/sharelist/plugins/drive.189cloud.js:72:34)
    at async prepare (/root/sharelist/plugins/drive.189cloud.js:298:46)
    at async Object.folder (/root/sharelist/plugins/drive.189cloud.js:347:19)
    at async process_fast (/root/sharelist/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/root/sharelist/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/root/sharelist/app/services/sharelist.js:112:20)
    at async Object.index (/root/sharelist/app/controllers/sharelist.js:186:18)
    at async /root/sharelist/app/router.js:29:7
    at async module.exports (/root/sharelist/app/middleware/koa-install.js:5:5)
    at async /root/sharelist/app/index.js:67:3
    at async /root/sharelist/app/index.js:63:3
    at async /root/sharelist/node_modules/koa-static-cache/index.js:53:36
    at async module.exports (/root/sharelist/app/middleware/koa-paths.js:168:3)

**Comment by yeheigcy** [comment]
https://github.com/reruin/sharelist/blob/e17ff4a90c1c004a830d61053c4f4703ceec42eb/plugins/drive.189cloud.js#L133

我这里把这个`url`改成`https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html`可以用，有没有其他问题就不知道了。

**Comment by at2008** [comment]
> https://github.com/reruin/sharelist/blob/e17ff4a90c1c004a830d61053c4f4703ceec42eb/plugins/drive.189cloud.js#L133
> 
> 我这里把这个`url`改成`https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html`可以用，有没有其他问题就不知道了。

感谢，试过了，的确可以正常使用，感谢！

**Comment by Easul** [comment]
> https://github.com/reruin/sharelist/blob/e17ff4a90c1c004a830d61053c4f4703ceec42eb/plugins/drive.189cloud.js#L133
> 
> 我这里把这个`url`改成`https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html`可以用，有没有其他问题就不知道了。

感谢,我的也好了 !

**Comment by Easul** [comment]
> > > https://github.com/reruin/sharelist/blob/e17ff4a90c1c004a830d61053c4f4703ceec42eb/plugins/drive.189cloud.js#L133
> > > 
> > > 我这里把这个`url`改成`https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html`可以用，有没有其他问题就不知道了。
> > 
> > 
> > 感谢，试过了，确实可以正常使用，感谢！
> 
> 请问具体改哪里，改了还行不行

改了之后pm2 restart all, 重启下就行了

**Comment by acgku** [comment]
> pm2 restart all
原来少了重启，非常感谢的确可以了谢谢

**Comment by iso-lib** [comment]
> https://github.com/reruin/sharelist/blob/e17ff4a90c1c004a830d61053c4f4703ceec42eb/plugins/drive.189cloud.js#L133
> 
> 我这里把这个`url`改成`https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html`可以用，有没有其他问题就不知道了。

docker版已试,,确实可行.,感谢.

**Comment by ferocknew** [comment]
的确可行，我已经更新代码重新编译了 docker

**Comment by ivkeji** [comment]
用heroku安装的的该在什么地方修改呢？

**Comment by reruin** [comment]
> 用heroku安装的的该在什么地方修改呢？

hero需重新安装
