### ISSUE TITLE
可以添加linux_arm64的二进制文件吗

### ISSUE THREAD

**Issue by lq-259** [reruin/sharelist#568]
### 需求描述 / Description of the feature

可以添加linux_arm64的二进制文件吗

**Comment by reruin** [comment]
可以。将会在后续的release中添加 linux-arm64的打包。

**Comment by lq-259** [comment]
> 可以。将会在后续的release中添加 linux-arm64的打包。

非常感谢

**Comment by iii80** [comment]
二进制可以给配置文件和插件做成外置，程序内置，可以方便升级修改插件

**Comment by reruin** [comment]
> 二进制可以给配置文件和插件做成外置，程序内置，可以方便升级修改插件

支持的。同目录下的cache文件夹中，存放有配置文件；plugins文件夹用于存放插件(此文件夹需手动创建)。

**Comment by reruin** [comment]
已添加，但 linux-arm64 未测试可用性。如果有问题 请反馈。

**Comment by lq-259** [comment]
> 已添加，但 linux-arm64 未测试可用性。如果有问题 请反馈。

好的，非常感谢

**Comment by lq-259** [comment]
> 已添加，但 linux-arm64 未测试可用性。如果有问题 请反馈。

启动显示这个：
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: Cannot find module '/snapshot/sharelist/node_modules/only/index'. Please verify that the package.json has a valid "main" entry
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at tryPackage (node:internal/modules/cjs/loader:347:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/snapshot/sharelist/node_modules/koa/lib/response.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1095:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/sharelist/node_modules/only/package.json',
  requestPath: 'only',
  pkg: true
}

**Comment by jmheqiao** [comment]
我的N1盒子coreelec的docker，无法运行，日志显示：Istandard_init_linux.go:211: exec user process caused "exec format error"
