### ISSUE TITLE
docker reruin/sharelist:next 无法正常启动

### ISSUE THREAD

**Issue by long1215** [reruin/sharelist#569]
### 问题描述 / Describe the bug

docker reruin/sharelist:next 无法正常启动

### 复现链接 / Reproduction

无

### 日志 / Logs

```shell
> sharelist@0.2.1 start /sharelist
> node app/index.js

(node:25) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at module.exports (/sharelist/node_modules/@sharelist/core/lib/index.js:117:36)
    at /sharelist/package/sharelist/index.js:29:26
    at async /sharelist/app/core/app.js:152:20
    at async App.hookLifeCycle (/sharelist/app/core/app.js:145:7)
    at async App.init (/sharelist/app/core/app.js:58:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> sharelist@0.2.1 start /sharelist
> node app/index.js

(node:25) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at module.exports (/sharelist/node_modules/@sharelist/core/lib/index.js:117:36)
    at /sharelist/package/sharelist/index.js:29:26
    at async /sharelist/app/core/app.js:152:20
    at async App.hookLifeCycle (/sharelist/app/core/app.js:145:7)
    at async App.init (/sharelist/app/core/app.js:58:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 404gods** [comment]
一样的问题，没法用

**Comment by sbwml** [comment]
开发中。。。。

**Comment by kwamenf** [comment]
latest 可以运行

**Comment by dzoer** [comment]
一样，不能启动

**Comment by iii80** [comment]
docker run -d -v /etc/sharelist:/sharelist/cache -p 33001:33001 --name="sharelist" reruin/sharelist:next  /sbin/init  可以启动 但是提示 can't open /dev/tty4: No such file or directory  不能登录

**Comment by cuijianzhuang** [comment]
一样，不能启动

**Comment by reruin** [comment]
已修复。
