### ISSUE TITLE
显示网站标题，没内容，一跑就100占用

### ISSUE THREAD

**Issue by 15601560** [reruin/sharelist#573]
### 问题描述 / Describe the bug

环境：宝塔 PM2
运行日志
2021-08-20T19:02:54: 2021-08-20T11:02:54.990Z
2021-08-20T19:02:54: Sharelist Server is running at http://127.0.0.1:33001/
2021-08-20T19:36:21: 2021-08-20T11:36:21.859Z
2021-08-20T19:36:21: Sharelist Server is running at http://127.0.0.1:33001/
2021-08-20T19:36:22: load ctc
2021-08-20T19:36:22: load aliyun
2021-08-20T19:36:22: load baidu
2021-08-20T19:36:22: load caiyun
2021-08-20T19:36:22: load file
2021-08-20T19:36:22: load googledrive
2021-08-20T19:36:22: load http
2021-08-20T19:36:22: load https
2021-08-20T19:36:22: load onedrive
2021-08-20T19:36:22: load sld

### 复现链接 / Reproduction

go.imgblz.cn

### 日志 / Logs

```shell
2021-08-20T19:18:44:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:44:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:44:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:44:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:44:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:44:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:44:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:44: }
2021-08-20T19:18:44: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:44: Require stack:
2021-08-20T19:18:44: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:44:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:44:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:44:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:44:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:44:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:44:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:44:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:44:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:44:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:44:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:44:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:44:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:44: }
2021-08-20T19:18:45: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:45: Require stack:
2021-08-20T19:18:45: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:45:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:45:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:45:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:45:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:45:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:45:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:45:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:45:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:45:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:45:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:45:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:45:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:45: }
2021-08-20T19:18:46: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:46: Require stack:
2021-08-20T19:18:46: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:46:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:46:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:46:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:46:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:46:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:46:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:46:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:46:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:46:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:46:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:46:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:46:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:46: }
2021-08-20T19:18:46: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:46: Require stack:
2021-08-20T19:18:46: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:46:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:46:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:46:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:46:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:46:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:46:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:46:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:46:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:46:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:46:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:46:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:46:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:46: }
2021-08-20T19:18:47: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:47: Require stack:
2021-08-20T19:18:47: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:47:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:47:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:47:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:47:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:47:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:47:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:47:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:47:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:47:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:47:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:47:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:47:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:47: }
2021-08-20T19:18:48: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:48: Require stack:
2021-08-20T19:18:48: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:48:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:48:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:48:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:48:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:48:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:48:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:48:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:48:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:48: }
2021-08-20T19:18:48: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:48: Require stack:
2021-08-20T19:18:48: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:48:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:48:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:48:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:48:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:48:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:48:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:48:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:48:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:48: }
2021-08-20T19:18:48: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:48: Require stack:
2021-08-20T19:18:48: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:48:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:48:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:48:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:48:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:48:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:48:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:48:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:48:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:48:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:48:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:48: }
2021-08-20T19:18:49: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:49: Require stack:
2021-08-20T19:18:49: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:49:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:49:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:49:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:49:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:49:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:49:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:49:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:49:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:49: }
2021-08-20T19:18:49: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:49: Require stack:
2021-08-20T19:18:49: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:49:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:49:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:49:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:49:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:49:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:49:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:49:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:49:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:49: }
2021-08-20T19:18:49: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:49: Require stack:
2021-08-20T19:18:49: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:49:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:49:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:49:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:49:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:49:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:49:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:49:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:49:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:49:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:49:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:49: }
2021-08-20T19:18:50: Error: Cannot find module '/www/wwwroot/go.imgblz.cn/sharelist/scripts/package.json'
2021-08-20T19:18:50: Require stack:
2021-08-20T19:18:50: - /www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js
2021-08-20T19:18:50:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-20T19:18:50:     at Module.Hook._require.Module.require (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
2021-08-20T19:18:50:     at require (internal/modules/cjs/helpers.js:92:18)
2021-08-20T19:18:50:     at Object.<anonymous> (/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js:21:13)
2021-08-20T19:18:50:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-20T19:18:50:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-20T19:18:50:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-20T19:18:50:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-20T19:18:50:     at Object.<anonymous> (/www/server/nvm/versions/node/v14.17.5/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-08-20T19:18:50:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2021-08-20T19:18:50:   code: 'MODULE_NOT_FOUND',
2021-08-20T19:18:50:   requireStack: [ '/www/wwwroot/go.imgblz.cn/sharelist/scripts/release.js' ]
2021-08-20T19:18:50: }
```

**Comment by 15601560** [comment]
用的是打包的二进制版本

**Comment by reruin** [comment]
这日志看着不像是打包版的。是从 这里下载的吗 https://github.com/reruin/sharelist/releases/download/v0.2.1/sharelist_linux_amd64.tar.gz

**Comment by 15601560** [comment]
是的，要不你私QQ1608683211帮我看看

**Comment by reruin** [comment]
方便的话，请将 后台地址 root 账号密码 私发至邮箱 reruin@gmail.com。

**Comment by 15601560** [comment]
已由作者解决
原因：反代
贴出来成功配置共参考
#PROXY-START/
location ~* \.(gif|png|jpg|css|js|woff|woff2)$
{
	proxy_pass http://127.0.0.1:33001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    expires 12h;
}
location /
{
    proxy_pass http://127.0.0.1:33001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
}

#PROXY-END/
