### ISSUE TITLE
arm64 无法运行

### ISSUE THREAD

**Issue by dzoer** [reruin/sharelist#584]
### 问题描述 / Describe the bug

下载arm64的二进制文件，启动时报错

### 日志 / Logs

```shell
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: Cannot find module '/snapshot/sharelist/node_modules/only/index'. Please verify that the package.json has a valid "main" entry
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at tryPackage (node:internal/modules/cjs/loader:347:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/snapshot/sharelist/node_modules/koa/lib/response.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1095:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/sharelist/node_modules/only/package.json',
  requestPath: 'only',
  pkg: true
}
```

**Comment by reruin** [comment]
arm64 的问题，将统一在 #568 中回复。

**Comment by reruin** [comment]
已修复。最新上release 已包含 arm64 arm7
