### ISSUE TITLE
用的编译好的版本0.2.5  配置好aliyunpan后程序崩溃

### ISSUE THREAD

**Issue by gaoluhua99** [reruin/sharelist#598]
### 问题描述 / Describe the bug

问题如题。

### Sharelist 版本 / Sharelist Version

v0.2

### 日志 / Logs

```shell
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
./sharelist_linux_amd64: /lib/libstdc++.so.6: no version information available (required by ./sharelist_linux_amd64)
2021-09-07T04:32:02.891Z
Sharelist Server is running at http://127.0.0.1:33001/
load ctc
load aliyun
load baidu
load caiyun
load file
load googledrive
load http
load https
load onedrive
load sld
load ctc
load aliyun
load baidu
load caiyun
load file
load googledrive
load http
load https
load onedrive
load sld
request retry 1 FetchError: network timeout at: https://api.aliyundrive.com/token/refresh
    at Timeout.<anonymous> (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1454:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'request-timeout'
}
request retry 0 FetchError: network timeout at: https://api.aliyundrive.com/token/refresh
    at Timeout.<anonymous> (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1454:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'request-timeout'
}
/snapshot/sharelist/packages/sharelist/plugins/driver.aliyundrive.js:42
        data.key = data.user_id = key = credentials.user_id
                                                    ^

TypeError: Cannot read property 'user_id' of undefined
    at Manager.init (/snapshot/sharelist/packages/sharelist/plugins/driver.aliyundrive.js:42:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by reruin** [comment]
应该是网络问题，重试下试试。

**Comment by gaoluhua99** [comment]
> 应该是网络问题，重试下试试。

家里的网络 ，我是远程操作家里的nas。网络应该没问题。
