### ISSUE TITLE
Error - 500

### ISSUE THREAD

**Issue by penjune** [reruin/sharelist#60]
Error
Looks like something broke!
TypeError: cache.save is not a function
    at Object.file (/app/sharelist-master/plugins/drive.gd.js:132:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

更新昨天的版本后无法下载，挂载的是google drive，部署在heroku上

**Comment by reruin** [comment]
一个缓存
bug ，已修复。

**Comment by penjune** [comment]
实测已恢复正常
非常感谢
