### ISSUE TITLE
天翼云盘 快一个星期进不去了  

### ISSUE THREAD

**Issue by Liuruicheng520** [reruin/sharelist#604]
### 问题描述 / Describe the bug

Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

### Sharelist 版本 / Sharelist Version

v0.2

### 日志 / Logs

```shell
Load Plugins:  drive.odc.api

Load Plugins:  drive.onedrive

Load Plugins:  drive.sftp

Load Plugins:  drive.teambition

Load Plugins:  drive.webdav

Load Plugins:  format.url

Load Plugins:  preview.document

Load Plugins:  preview.media

Load Plugins:  preview.torrent

Load endpoints: RSS Server

SMB logger init

Load endpoints: SMBServer

Load endpoints: WeApp Server

Load endpoints: WebDAVServer

2021-09-18T07:23:25.423Z

App is running at http://127.0.0.1:33001/

  <-- GET /

  --> GET / 200 113ms 2.92kb

  <-- GET /style/main.css?1631949805229

  <-- GET /script/main.js?1631949805229

  --> GET /script/main.js?1631949805229 200 20ms 2.25kb

  --> GET /style/main.css?1631949805229 200 39ms 10.87kb

  <-- GET /lrc

needcaptcha: false

  xxx GET /lrc 500 1,763ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /lxy

needcaptcha: false

  xxx GET /lxy 500 1,773ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /lcp

needcaptcha: false

  xxx GET /lcp 500 1,485ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /manage

  --> GET /manage 200 200ms 2.68kb

  <-- POST /manage/api

  --> POST /manage/api 200 1ms 55b

  <-- GET /manage

  --> GET /manage 200 135ms 15.8kb

  <-- POST /manage/api

  --> POST /manage/api 200 1ms 53b

  <-- GET /

  --> GET / 200 78ms 2.92kb

  <-- GET /lrc

  --> GET /lrc 200 20ms 1.34kb

  <-- POST /lrc

needcaptcha: false

  --> POST /lrc 302 1,147ms 91b

  <-- GET /lrc

  xxx GET /lrc 500 485ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /lrc

  xxx GET /lrc 500 435ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /

  --> GET / 200 45ms 2.92kb

  <-- GET /lrc

  xxx GET /lrc 500 551ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)



  <-- GET /

  --> GET / 200 41ms 2.92kb

  <-- GET /lrc

  xxx GET /lrc 500 509ms -



  TypeError: data.body.data is not iterable

      at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by reruin** [comment]
天翼云改接口了。节后会更新。
