### ISSUE TITLE
天翼云报错了 

### ISSUE THREAD

**Issue by leweiboy** [reruin/sharelist#608]
### 问题描述 / Describe the bug

Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (C:\Program Files\nodejs\sharelist\plugins\drive.189cloud.js:384:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async process_fast (C:\Program Files\nodejs\sharelist\app\plugins\cmd.core.js:187:17)
    at async Object.ls (C:\Program Files\nodejs\sharelist\app\plugins\cmd.core.js:55:16)
    at async ShareList.path (C:\Program Files\nodejs\sharelist\app\services\sharelist.js:112:20)
    at async Object.index (C:\Program Files\nodejs\sharelist\app\controllers\sharelist.js:186:18)
    at async C:\Program Files\nodejs\sharelist\app\router.js:29:7
    at async module.exports (C:\Program Files\nodejs\sharelist\app\middleware\koa-install.js:5:5)
    at async C:\Program Files\nodejs\sharelist\app\index.js:67:3
    at async C:\Program Files\nodejs\sharelist\app\index.js:63:3
    at async C:\Program Files\nodejs\sharelist\node_modules\koa-static-cache\index.js:53:36
    at async module.exports (C:\Program Files\nodejs\sharelist\app\middleware\koa-paths.js:168:3)
        
      

### Sharelist 版本 / Sharelist Version

v0.1

**Comment by shouji123** [comment]
同样，折腾半天也没解决，报错为：

Error
Looks like something broke!
        
TypeError: data.body.data is not iterable
    at Object.folder (/root/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by at2008** [comment]
同样的问题

**Comment by YIMUYIGUO** [comment]
一样的   没解决

**Comment by YIMUYIGUO** [comment]
应该是Js问题
TypeError: data.body.data is not iterable
    at Object.folder (/www/wwwroot/pan.bimjcw.com/plugins/drive.189cloud.js:384:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async process_fast (/www/wwwroot/pan.bimjcw.com/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/www/wwwroot/pan.bimjcw.com/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/www/wwwroot/pan.bimjcw.com/app/services/sharelist.js:112:20)
    at async Object.index (/www/wwwroot/pan.bimjcw.com/app/controllers/sharelist.js:186:18)
    at async /www/wwwroot/pan.bimjcw.com/app/router.js:29:7
    at async module.exports (/www/wwwroot/pan.bimjcw.com/app/middleware/koa-install.js:5:5)
    at async /www/wwwroot/pan.bimjcw.com/app/index.js:67:3
    at async /www/wwwroot/pan.bimjcw.com/app/index.js:63:3
    at async /www/wwwroot/pan.bimjcw.com/node_modules/koa-static-cache/index.js:53:36
    at async module.exports (/www/wwwroot/pan.bimjcw.com/app/middleware/koa-paths.js:168:3)

**Comment by nitsort** [comment]
[drive.189cloud.js.zip](https://github.com/reruin/sharelist/files/7236898/drive.189cloud.js.zip)
ShareList 版本：v0.1
可以暂时凑合用一下，根据天翼云盘WEB端改的。

**Comment by YIMUYIGUO** [comment]
谢谢 收到
| |
李丹阳
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年9月27日 ***@***.***> 写道：

drive.189cloud.js.zip
ShareList 版本：v0.1
可以暂时凑合用一下，根据天翼云盘WEB端改的。

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by at2008** [comment]
> [drive.189cloud.js.zip](https://github.com/reruin/sharelist/files/7236898/drive.189cloud.js.zip)
> ShareList 版本：v0.1
> 可以暂时凑合用一下，根据天翼云盘WEB端改的。
> 需要重启和清缓存。

谢谢，可以用

**Comment by ferocknew** [comment]
> > [drive.189cloud.js.zip](https://github.com/reruin/sharelist/files/7236898/drive.189cloud.js.zip)
> > ShareList 版本：v0.1
> > 可以暂时凑合用一下，根据天翼云盘WEB端改的。
> > 需要重启和清缓存。
> 
> 谢谢，可以用



有没有兴趣开一个 git 仓库，一起维护 sharelist 的驱动插件。互相交流？

**Comment by at2008** [comment]
> > > [drive.189cloud.js.zip](https://github.com/reruin/sharelist/files/7236898/drive.189cloud.js.zip)
> > > ShareList 版本：v0.1
> > > 可以暂时凑合用一下，根据天翼云盘WEB端改的。
> > > 需要重启和清缓存。
> > 
> > 
> > 谢谢，可以用
> 
> 有没有兴趣开一个 git 仓库，一起维护 sharelist 的驱动插件。互相交流？

有兴趣，缺乏动手能力呀 i😊

**Comment by dmlt** [comment]
Error
Looks like something broke!

        
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.folder (/www/wwwroot/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

替换了 还是不行。

**Comment by wnark** [comment]
> [drive.189cloud.js.zip](https://github.com/reruin/sharelist/files/7236898/drive.189cloud.js.zip) ShareList 版本：v0.1 可以暂时凑合用一下，根据天翼云盘WEB端改的。 需要重启和清缓存。

失效了。报错：

```
Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (/root/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by reruin** [comment]
0.1 和 新版 均已修复。
