### ISSUE TITLE
天翼网盘报错，论坛里有大量网友都反馈了这个问题...

### ISSUE THREAD

**Issue by shouji123** [reruin/sharelist#609]
### 问题描述 / Describe the bug

Error
Looks like something broke!

TypeError: data.body.data is not iterable
    at Object.folder (/root/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

### Sharelist 版本 / Sharelist Version

v0.1

**Comment by shouji123** [comment]
已解决，有点复杂...
