### ISSUE TITLE
天翼云无法挂载

### ISSUE THREAD

**Issue by xuange-dada** [reruin/sharelist#615]
### 问题描述 / Describe the bug

什么时候更新一下，用的Heroku版，天翼云接口失效

### Sharelist 版本 / Sharelist Version

v0.2

### 日志 / Logs

```shell
Error
Looks like something broke!

        
TypeError: data.body.data is not iterable
    at Object.folder (/sharelist/plugins/drive.189cloud.js:384:33)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by reruin** [comment]
已修复。
