### ISSUE TITLE
大佬可以修复一下老版本的天翼云吗？

### ISSUE THREAD

**Issue by qingtian110** [reruin/sharelist#626]
### 问题描述 / Describe the bug

老版本天翼云登录错误 500

### Sharelist 版本 / Sharelist Version

v0.1

### 日志 / Logs

```shell
Error 500
Looks like something broke!


TypeError: data.body.data is not iterable
    at Object.folder (/opt/sharelist/plugins/drive.189cloud.js:384:33)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async process_fast (/opt/sharelist/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/opt/sharelist/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/opt/sharelist/app/services/sharelist.js:112:20)
    at async Object.index (/opt/sharelist/app/controllers/sharelist.js:186:18)
    at async /opt/sharelist/app/router.js:29:7
    at async module.exports (/opt/sharelist/app/middleware/koa-install.js:5:5)
    at async /opt/sharelist/app/index.js:67:3
    at async /opt/sharelist/app/index.js:63:3
    at async /opt/sharelist/node_modules/koa-static-cache/index.js:53:36
    at async module.exports (/opt/sharelist/app/middleware/koa-paths.js:168:3)
```

**Comment by reruin** [comment]
已修复。
