### ISSUE TITLE
v0.3.4 二进制安装，.passwd增加密码后。加密路径报错500.

### ISSUE THREAD

**Issue by CatCars** [reruin/sharelist#631]
### 问题描述 / Describe the bug

.passwd增加密码后。

能正常显示密码输入框.输入正确后显示500

### 日志 / Logs

```shell
type: basic
data:
  - 1234561
  - abcdef
Trace: ReferenceError: req is not defined
    at /snapshot/sharelist/packages/sharelist/plugins/auth.js:37:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /snapshot/sharelist/packages/sharelist-core/lib/index.js:104:16
    at async forwardTrack (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:553:15)
    at async Object.list (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:160:63)
    at async Object.getFiles (/snapshot/sharelist/packages/sharelist/package/sharelist/utils.js:36:12)
    at async Controller.list (/snapshot/sharelist/packages/sharelist/app/controller/api.js:118:27)
    at async /snapshot/sharelist/packages/sharelist/package/webdav/index.js:196:11
    at async cors (/snapshot/sharelist/node_modules/@koa/cors/index.js:98:16)
    at Object.getFiles (/snapshot/sharelist/packages/sharelist/package/sharelist/utils.js:38:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Controller.list (/snapshot/sharelist/packages/sharelist/app/controller/api.js:118:27)
    at async /snapshot/sharelist/packages/sharelist/package/webdav/index.js:196:11
    at async cors (/snapshot/sharelist/node_modules/@koa/cors/index.js:98:16)

**Comment by reruin** [comment]
已修复
