### ISSUE TITLE
显示README.md内容的bug

### ISSUE THREAD

**Issue by wekingchen** [reruin/sharelist#64]
同一个谷歌网盘的源，使用分享ID挂载时，可以正常显示README.md的内容。而在使用官方API挂载时，出现错误无法显示。错误信息如下：

Error
Looks like something broke!

TypeError: Cannot destructure property `req` of 'undefined' or 'null'.
    at prepare (/root/sharelist/plugins/drive.gd.api.js:252:19)
    at Object.file (/root/sharelist/plugins/drive.gd.api.js:316:25)
    at getSource (/root/sharelist/app/services/plugin.js:49:26)
    at ShareList.source (/root/sharelist/app/services/sharelist.js:155:18)
    at Object.index (/root/sharelist/app/controllers/sharelist.js:109:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by reruin** [comment]
已修复。

**Comment by wekingchen** [comment]
@reruin 还是不对，直接变挂载失败了，信息如下：

挂载 GoogleDrive 失败
失败请重试。原因：Bad Request
点此重新开始

**Comment by wekingchen** [comment]
@reruin 大概知道什么原因了，是这次更新新加了回调地址这个参数的原因吧。请问这个地址应该怎么填呢？

**Comment by wekingchen** [comment]
经过几次重新绑定，几次都失败之后，用原来没带回调地址的参数，神奇的挂载成功了。而且目录下的README.md文件显示也正常了，但还有一个错误是，点击这个README.md文件进去还是错的：

Error
Looks like something broke!

TypeError: Cannot read property 'split' of undefined
    at getCredentials (/root/sharelist/plugins/drive.gd.api.js:245:29)
    at prepare (/root/sharelist/plugins/drive.gd.api.js:259:39)
    at Object.file (/root/sharelist/plugins/drive.gd.api.js:404:25)
    at getSource (/root/sharelist/app/services/plugin.js:49:26)
    at Object.markdown [as md] (/root/sharelist/plugins/preview.document.js:13:32)
    at getPreview (/root/sharelist/app/services/plugin.js:91:51)
    at ShareList.preview (/root/sharelist/app/services/sharelist.js:144:18)
    at output (/root/sharelist/app/controllers/sharelist.js:20:28)
    at Object.index (/root/sharelist/app/controllers/sharelist.js:122:15)
    at <anonymous>

**Comment by wekingchen** [comment]
还是不对，重启程序之后，又挂载失败要求重新绑定了：（

**Comment by reruin** [comment]
请更新最新代码，再试试。

**Comment by wekingchen** [comment]
抱歉前几天一直卡在Google Drive API挂在上没能测试，今天搞好了。新代码下，点击README.md文件进去还是错的：
Error
Looks like something broke!

TypeError: Cannot read property 'split' of undefined
    at getCredentials (/root/sharelist/plugins/drive.gd.api.js:284:29)
    at prepare (/root/sharelist/plugins/drive.gd.api.js:298:39)
    at Object.file (/root/sharelist/plugins/drive.gd.api.js:470:25)
    at getSource (/root/sharelist/app/services/plugin.js:49:26)
    at Object.markdown [as md] (/root/sharelist/plugins/preview.document.js:13:32)
    at getPreview (/root/sharelist/app/services/plugin.js:91:51)
    at ShareList.preview (/root/sharelist/app/services/sharelist.js:144:18)
    at output (/root/sharelist/app/controllers/sharelist.js:20:28)
    at Object.index (/root/sharelist/app/controllers/sharelist.js:122:15)
    at <anonymous>

**Comment by reruin** [comment]
已修复。

**Comment by wekingchen** [comment]
@reruin 抓了最新代码，程序开不起来了。

**Comment by reruin** [comment]
移除目录 重新安装一次。不要用update.sh

**Comment by wekingchen** [comment]
好的，bug确认ok了。
