### ISSUE TITLE
Onedrive 404 错误

### ISSUE THREAD

**Issue by suzanneeound** [reruin/sharelist#640]
### 问题描述 / Describe the bug

绑定 onedrive 后，增加了 .passwd 密码文件。

问题1:
点击文件夹后，会出现 404 错误。此时返回根目录，点击文件夹，会弹出验证页面，输入密码后该文件夹打开，再点击子文件夹，又出现404。

问题2:
pdf 无法预览。

### Sharelist 版本 / Sharelist Version

v0.3.8

### 日志 / Logs

```shell
Trace: { code: 404, message: "Can't find [undefined] folder" }
    at Object.exports.getFiles (/sharelist/package/sharelist/utils.js:38:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Controller.list (/sharelist/app/controller/api.js:118:27)
    at async cors (/sharelist/node_modules/@koa/cors/index.js:98:16)
```

**Comment by zhtok** [comment]
### 问题描述 / Describe the bug
绑定本地磁盘后，增加了 .passwd 密码文件。

### 问题:
点击文件夹后，会出现 404 错误。此时返回根目录，点击文件夹，会弹出验证页面，输入密码后该文件夹打开，再点击子文件夹，又出现404。

### Sharelist 版本 / Sharelist Version
v0.3.15@docker

### 复现链接 / Reproduction
未穿透到公网，无

### 日志 / Logs
```
Trace: { code: 404, message: "Can't find [undefined] folder" }
    at Object.exports.getFiles (/sharelist/package/sharelist/utils.js:38:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Controller.list (/sharelist/app/controller/api.js:118:27)
    at async cors (/sharelist/node_modules/@koa/cors/index.js:98:16)
```

**Comment by J3n5en** [comment]
#822
