### ISSUE TITLE
Docker容器启动失败

### ISSUE THREAD

**Issue by ngfchl** [reruin/sharelist#651]
### 问题描述 / Describe the bug

容器创建成功，但是启动失败，难道是我启动的不对？
```
sharelist
reruin/sharelist:latest
EXITED (1)



> sharelist@0.1.0 start /sharelist
> node app.js

Load Plugins:  auth.basic
Load Plugins:  cmd.copy
Load Plugins:  cmd.core
Load Plugins:  drive.fs
Load Plugins:  drive.http
Load Plugins:  drive.https
Load Plugins:  drive.lb
Load Plugins:  drive.sld
Load Plugins:  drive.189cloud.api
Load Plugins:  drive.189cloud.business
Load Plugins:  drive.189cloud.home
/sharelist/plugins/drive.189cloud.js:472
      if (data.body.fileListAO?.folderList) {
                               ^
SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at load (/sharelist/app/services/plugin.js:331:19)
    at loader (/sharelist/app/services/plugin.js:414:5)
    at Object.<anonymous> (/sharelist/app/index.js:29:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharelist@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharelist@0.1.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-14T07_19_49_737Z-debug.log
```

### Sharelist 版本 / Sharelist Version

latest

**Comment by ngfchl** [comment]
不知是何原因，刚好升级0.37解决
