### ISSUE TITLE
v0.1版本和彩云登录报错

### ISSUE THREAD

**Issue by Immortal68** [reruin/sharelist#696]
### 问题描述 / Describe the bug

和彩云接入填入手机号，接收验证码提示参数错误，然后我去和彩云官网发送验证码，接收后填入sharelist，收到报错

### Sharelist 版本 / Sharelist Version

v0.1

### 日志 / Logs

```shell
Error
Looks like something broke!

        
TypeError: Cannot read property 'result' of null
    at Manager.create (/snapshot/sharelist_drive/plugins/drive.caiyun.js:530:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Manager.prepare (/snapshot/sharelist_drive/plugins/drive.caiyun.js:604:20)
    at async CY.path (/snapshot/sharelist_drive/plugins/drive.caiyun.js:726:16)
    at async CY.folder (/snapshot/sharelist_drive/plugins/drive.caiyun.js:900:12)
    at async process_fast (/snapshot/sharelist_drive/app/plugins/cmd.core.js:187:17)
    at async Object.ls (/snapshot/sharelist_drive/app/plugins/cmd.core.js:55:16)
    at async ShareList.path (/snapshot/sharelist_drive/app/services/sharelist.js:112:20)
    at async Object.index (/snapshot/sharelist_drive/app/controllers/sharelist.js:186:18)
    at async /snapshot/sharelist_drive/app/router.js:29:7
    at async /snapshot/sharelist_drive/app/middleware/koa-install.js:5:5
    at async /snapshot/sharelist_drive/app/index.js:67:3
    at async /snapshot/sharelist_drive/app/index.js:63:3
    at async /snapshot/sharelist_drive/node_modules/koa-static-cache/index.js:39:63
    at async /snapshot/sharelist_drive/app/middleware/koa-paths.js:168:3
```

**Comment by hbqjren** [comment]
一切正常。我用的是heroku
