### ISSUE TITLE
rclone连接webdav，服务端报404错误

### ISSUE THREAD

**Issue by karma-sun** [reruin/sharelist#709]
### 问题描述 / Describe the bug

rclone连接webdav，服务端报404错误
服务端使用下载的release 0.3.11版本，使用默认配置

### Sharelist 版本 / Sharelist Version

next

### 日志 / Logs

```shell
[WebDAV] PROPFIND /webdav/ <--> ::ffff:127.0.0.1

  Error: non-error thrown: {"code":404,"message":"Can't find [webdav] folder"}
      at Object.onerror (/snapshot/sharelist/node_modules/koa/lib/context.js:119:31)
      at onerror (/snapshot/sharelist/node_modules/koa/lib/application.js:165:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by reruin** [comment]
使用 0.3.15 再试试

**Comment by karma-sun** [comment]
0.3.15版本运行正常
