### ISSUE TITLE
挂载Google Drive视频预览出现问题

### ISSUE THREAD

**Issue by aumk** [reruin/sharelist#77]
Error
Looks like something broke!

        
TypeError: Cannot read property 'preview' of undefined
    at getPreview (/srv/http/sharelist/app/services/plugin.js:98:31)
    at ShareList.preview (/srv/http/sharelist/app/services/sharelist.js:74:18)
    at output (/srv/http/sharelist/app/controllers/sharelist.js:20:28)
    at Object.index (/srv/http/sharelist/app/controllers/sharelist.js:128:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /srv/http/sharelist/app/routers/page.js:14:7
    at async module.exports (/srv/http/sharelist/app/middleware/koa-install.js:5:5)
    at async /srv/http/sharelist/app/index.js:70:3
    at async module.exports (/srv/http/sharelist/app/middleware/koa-paths.js:88:3)
    at async module.exports (/srv/http/sharelist/app/middleware/koa-addr.js:16:3)

挂载本地目录预览视频正常

**Comment by reruin** [comment]
已修复，再试试。
