### ISSUE TITLE
天翼云提示500”设备ID不存在，需要二次设备校验“，请问有大佬知道怎么解决吗

### ISSUE THREAD

**Issue by michealhansun** [reruin/sharelist#784]
### 问题描述 / Describe the bug

天翼云提示500”设备ID不存在，需要二次设备校验“，请问有大佬知道怎么解决吗

### Sharelist 版本 / Sharelist Version

next

### 日志 / Logs

```shell
stdout: [WebDAV] PROPFIND /cloud/189/ <--> ::ffff:192.168.1.2
stderr: 
stderr:   Error: non-error thrown: {"message":"设备ID不存在，需要二次设备校验"}
stderr:       at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
stderr:       at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
stderr:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
stderr:
```

**Comment by michealhansun** [comment]
找到方法了，修改一次密码就可以解决了，可以正常登录

**Comment by qqzwc** [comment]
不应该是关闭设备锁吗，就像这里：https://github.com/vistal8/tianyiyun
