### ISSUE TITLE
天翼云无法访问

### ISSUE THREAD

**Issue by kettly1260** [reruin/sharelist#785]
### 问题描述 / Describe the bug

 使用过密码和cookie两种方式登录，但是均无法进入目录。点进去都是空的

### Sharelist 版本 / Sharelist Version

v0.3.15

### 日志 / Logs

```shell
ctc://xxxxxxxx/-11#list

  URIError: URI malformed
      at decodeURIComponent (<anonymous>)
      at /snapshot/sharelist/packages/sharelist/package/sharelist/utils.js:45:23
      at Array.filter (<anonymous>)
      at Object.getFiles (/snapshot/sharelist/packages/sharelist/package/sharelist/utils.js:44:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Controller.list (/snapshot/sharelist/packages/sharelist/app/controller/api.js:150:27)
      at async /snapshot/sharelist/packages/sharelist/package/webdav/index.js:237:9
      at async cors (/snapshot/sharelist/node_modules/@koa/cors/index.js:98:16)
```

**Comment by kettly1260** [comment]
F12查看发现list报500访问错误：https://website.com/api/drive/list
