### ISSUE TITLE
阿里云 挂webdav好像又问题，

### ISSUE THREAD

**Issue by maryjeck** [reruin/sharelist#796]
### 问题描述 / Describe the bug

[WebDAV] MKCOL /webdav/%E9%98%BF%E9%87%8C%E4%BA%91/ <--> ::ffff:127.0.0.1

  Error: non-error thrown: {"code":501,"message":"Not implemented"}
      at Object.onerror (C:\snapshot\sharelist\node_modules\koa\lib\context.js:119:31)
      at onerror (C:\snapshot\sharelist\node_modules\koa\lib\application.js:165:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Sharelist 版本 / Sharelist Version

next

### 日志 / Logs

```shell
[WebDAV] MKCOL /webdav/%E9%98%BF%E9%87%8C%E4%BA%91/ <--> ::ffff:127.0.0.1

  Error: non-error thrown: {"code":501,"message":"Not implemented"}
      at Object.onerror (C:\snapshot\sharelist\node_modules\koa\lib\context.js:119:31)
      at onerror (C:\snapshot\sharelist\node_modules\koa\lib\application.js:165:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by maryjeck** [comment]
发现问题了。rclone挂载webdav后，不能在里面创建文件例如office的临时文件，创建了就一致是这个提示
aliyun-webdav不会提示。而且也挺快的

**Comment by maryjeck** [comment]
/sbin/mount.davfs: warning: the server does not support locks
