### ISSUE TITLE
天翼云是否出现了限制流媒体播放？

### ISSUE THREAD

**Issue by xxyxxvii** [reruin/sharelist#802]
### 问题描述 / Describe the bug

无法播放大于1G的视频文件。

### Sharelist 版本 / Sharelist Version

next

### 日志 / Logs

```shell
Error: non-error thrown: {"message":"File too large"}
      at Object.onerror (/sharelist/node_modules/koa/lib/context.js:119:31)
      at onerror (/sharelist/node_modules/koa/lib/application.js:165:32)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by lewis1573** [comment]
我也遇到了同样的问题，下载大于1g的文件返回500，“File too large"

**Comment by ahdiua** [comment]
同样

**Comment by lewis1573** [comment]
貌似是天翼云盘官方api升级了，网页版不再支持1g以上文件，有人使用pc客户端的api解决了这个问题，不知道哪位大佬能加进去吗？[https://github.com/Xhofe/alist/pull/715](https://github.com/Xhofe/alist/pull/715)

**Comment by reruin** [comment]
等待修复，相关#810。
