### ISSUE TITLE
windows下webdav无法挂载

### ISSUE THREAD

**Issue by LINJIE9865** [reruin/sharelist#820]
### 问题描述 / Describe the bug

使用potplayer可以挂载webdav。
但是使用windows自带的“添加一个网络位置”,raidrive,浏览器直接访问webdav地址均无法访问。
浏览器提示404
  Error: non-error thrown: {"code":404}
      at Object.onerror (C:\snapshot\sharelist\node_modules\koa\lib\context.js:119:31)
      at onerror (C:\snapshot\sharelist\node_modules\koa\lib\application.js:165:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

windows自带和raidrive仅提示[WebDAV] PROPFIND /webdav <--> ::ffff:127.0.0.1。但在失败后没有后续。

### Sharelist 版本 / Sharelist Version

next

### 复现链接 / Reproduction

wbbdav路径设置为/webdav
账号密码为默认。
使用frps中转

### 日志 / Logs

```shell
2022-04-23T04:08:51.098Z
Sharelist Server is running at http://127.0.0.1:33001/
load ctc
load aliyun
load baidu
load caiyun
load file
load googledrive
load http
load https
load onedrive
load sld
[WebDAV] PROPFIND /webdav <--> ::ffff:127.0.0.1
[WebDAV] PROPFIND /webdav <--> ::ffff:127.0.0.1
[WebDAV] GET /webdav <--> ::ffff:127.0.0.1

  Error: non-error thrown: {"code":404}
      at Object.onerror (C:\snapshot\sharelist\node_modules\koa\lib\context.js:119:31)
      at onerror (C:\snapshot\sharelist\node_modules\koa\lib\application.js:165:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by zjy2931** [comment]
一样的问题
