### ISSUE TITLE
挂载OneDrive share报错 request retry 1 TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by hui99995** [reruin/sharelist#830]
### 问题描述 / Describe the bug

已经授权
网页端返回500错误
500
[undefined] The error occurred during the request.
服务端返回错误
request retry 1 TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1327:9)
    at /snapshot/sharelist/node_modules/node-fetch/lib/index.js:1432:19
    at new Promise (<anonymous>)
    at fetch (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1429:9)
    at request (/snapshot/sharelist/packages/sharelist-core/lib/request.js:118:23)
    at AsyncFunction.get (/snapshot/sharelist/packages/sharelist-core/lib/request.js:146:33)
    at Driver.list (/snapshot/sharelist/packages/sharelist/plugins/driver.onedrive.js:360:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async listById (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:487:17)
    at async forwardTrack (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:550:13)
request retry 0 TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1327:9)
    at /snapshot/sharelist/node_modules/node-fetch/lib/index.js:1432:19
    at new Promise (<anonymous>)
    at fetch (/snapshot/sharelist/node_modules/node-fetch/lib/index.js:1429:9)
    at request (/snapshot/sharelist/packages/sharelist-core/lib/request.js:118:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.list (/snapshot/sharelist/packages/sharelist/plugins/driver.onedrive.js:360:20)
    at async listById (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:487:17)
    at async forwardTrack (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:550:13)
    at async Object.list (/snapshot/sharelist/packages/sharelist-core/lib/driver.js:159:63)

### Sharelist 版本 / Sharelist Version

next

**Comment by reruin** [comment]
可以提供下share的链接吗？
